# Generated by Django 5.0.4 on 2024-06-27 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_solicitud_comuna_and_more'),
        ('login', '0006_alter_client_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudproducto',
            name='user',
        ),
        migrations.AddField(
            model_name='solicitudproducto',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.client'),
            preserve_default=False,
        ),
    ]
