# Generated by Django 5.0.4 on 2024-07-06 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_solicitudproducto_client_and_more'),
        ('crud', '0005_product_price'),
        ('login', '0008_user_verification_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(verbose_name='Total')),
                ('status', models.CharField(max_length=25, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user')),
            ],
            options={
                'verbose_name': 'solicitud producto',
                'verbose_name_plural': 'solicitudes productos',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('unit_price', models.PositiveIntegerField(verbose_name='Precio unitario')),
                ('subtotal', models.PositiveIntegerField(verbose_name='Subtotal')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.product')),
            ],
            options={
                'verbose_name': 'detalle solicitud',
                'verbose_name_plural': 'detalle solicitudes',
            },
        ),
        migrations.DeleteModel(
            name='SolicitudProducto',
        ),
    ]
