# Generated by Django 5.0.4 on 2024-07-06 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_order_orderdetail_delete_solicitudproducto'),
        ('crud', '0005_product_price'),
        ('login', '0008_user_verification_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'pedido', 'verbose_name_plural': 'pedidos'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PC', 'Pendiente Confirmación'), ('CF', 'Confirmado'), ('EP', 'En preparación'), ('EN', 'Entregado'), ('CN', 'Cancelado')], default='PC', max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.product', verbose_name='Producto'),
        ),
    ]
