# Generated by Django 5.0.4 on 2024-06-27 03:33

import django.db.models.deletion
import login.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_user_comuna_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='user',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default=1, max_length=250, verbose_name='Clave'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='NOMBRE')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='APELLIDO')),
                ('birthday', models.DateField(default=login.models.default_birthday, verbose_name='FECHA DE NACIMIENTO')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='TELÉFONO')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('SE', 'Sin especificar')], default='SE', max_length=2, verbose_name='GÉNERO')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
                ('comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.comuna', verbose_name='COMUNA')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.client', verbose_name='CLIENTE'),
        ),
    ]
