# Generated by Django 5.0.4 on 2024-06-27 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_remove_user_birthday_remove_user_comuna_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
    ]
