# Generated by Django 5.0.4 on 2024-06-27 04:35

import django.db.models.deletion
import login.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_solicitudproducto_client_and_more'),
        ('login', '0006_alter_client_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='client',
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=login.models.default_birthday, verbose_name='FECHA DE NACIMIENTO'),
        ),
        migrations.AddField(
            model_name='user',
            name='comuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.comuna', verbose_name='COMUNA'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('SE', 'Sin especificar')], default='SE', max_length=2, verbose_name='GÉNERO'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='APELLIDO'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='NOMBRE'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='TELÉFONO'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=100, unique=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Clave'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
