# Generated by Django 5.0.4 on 2024-06-27 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cameras',
        ),
        migrations.RemoveField(
            model_name='product',
            name='channels',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default=1, max_length=25, verbose_name='Categoría'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='flavor',
            field=models.CharField(default=1, max_length=25, verbose_name='Sabor'),
            preserve_default=False,
        ),
    ]
