# Generated by Django 5.0.4 on 2024-06-27 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_remove_product_cameras_remove_product_channels_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(max_length=100, verbose_name='FLAVOR')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('GA', 'Galletas'), ('PA', 'Pasteles'), ('DE', 'Desayuno')], default='GA', max_length=2, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='product',
            name='flavor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.flavor', verbose_name='Sabor'),
        ),
    ]
