# Generated by Django 5.0.4 on 2024-06-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_flavor_alter_product_category_alter_product_flavor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flavor',
            options={'verbose_name': 'sabor', 'verbose_name_plural': 'sabores'},
        ),
        migrations.AlterField(
            model_name='flavor',
            name='flavor',
            field=models.CharField(max_length=100, verbose_name='SABOR'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='flavor',
        ),
        migrations.AddField(
            model_name='product',
            name='flavor',
            field=models.ManyToManyField(blank=True, to='crud.flavor', verbose_name='Sabor'),
        ),
    ]
