# Generated by Django 5.0.4 on 2024-07-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_alter_flavor_options_alter_flavor_flavor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=1, verbose_name='Precio'),
            preserve_default=False,
        ),
    ]
